FROM golang:1.21

WORKDIR /build
COPY go-api/go.mod ./
COPY go-api/main.go ./
COPY go-api/main_test.go ./
RUN go get github.com/gin-gonic/gin@v1.9.1 && \
    go get gopkg.in/yaml.v3@v3.0.1 && \
    go get github.com/stretchr/testify@v1.8.4

RUN CGO_ENABLED=0 GOOS=linux go test -v ./...

FROM alpine:3.18
COPY --from=0 /build/jira-api .
CMD ["sh"]